export const LLM_MODELS = [
  {
    name: 'Gemini Pro 1.5',
    icon: '/icons/gemini.svg',
    value: 'gemini-1.5-pro-preview-0514',
    price: 7,
    smart: 3.5,
    speed: 2.5,
  },
  {
    name: 'LLama 3',
    icon: '/icons/llma.svg',
    value: 'groq/llama3-70b-8192',
    price: 0.9,
    smart: 3.2,
    speed: 4,
  },
  {
    name: 'GPT 4o',
    icon: '/icons/gpt.svg',
    value: 'gpt-4o-2024-05-13',
    price: 10,
    smart: 4.5,
    speed: 1.5,
  },
  {
    name: 'Claude 3 (Opus)',
    icon: '/icons/claude.svg',
    value: 'anthropic.claude-3-opus-20240229-v1:0',
    price: 15,
    smart: 4.5,
    speed: 2,
  },
  {
    name: 'Claude 3 (Sonnet)',
    icon: '/icons/claude.svg',
    value: 'anthropic.claude-3-sonnet-20240229',
    price: 3,
    speed: 3.2,
    smart: 4,
  },
];
