export enum TASK_TYPE {
  FOLLOW_UP_INFORMATION = "FOLLOW_UP_INFORMATION",
  FOLLOW_UP_FILE_INFORMATION = "FOLLOW_UP_FILE_INFORMATION",
  SYSTEM_CRAWL_ANALYSE = "SYSTEM_CRAWL_ANALYSE",
  SYSTEM_SEARCH_ENGINE = "SYSTEM_SEARCH_ENGINE",
  SYSTEM_COMPOSE = "SYSTEM_COMPOSE",
  SYSTEM_COMPOSE_AUDIO = "SYSTEM_COMPOSE_AUDIO",
  SYSTEM_COMPOSE_IMAGE = "SYSTEM_COMPOSE_IMAGE",
  SYSTEM_COMPOSE_VIDEO = "SYSTEM_COMPOSE_VIDEO",
  SYSTEM_DATA_INTEGRATION = "SYSTEM_DATA_INTEGRATION",
  CUSTOM_ACTION = "CUSTOM_ACTION",
  VIRTUAL_NODE = "VIRTUAL_NODE",
  AI_REVISE_PROBLEM_FROM_FOLLOW_UP = "AI_REVISE_PROBLEM_FROM_FOLLOW_UP",
  STARTING_NODE = "STARTING_NODE",
  SYSTEM_PROMPT_COMPOSE_OUTLINE = "SYSTEM_PROMPT_COMPOSE_OUTLINE",
  SYSTEM_SQL_ANALYSIS = "SYSTEM_SQL_ANALYSIS",
  SYSTEM_SQL_INSIGHT = "SYSTEM_SQL_INSIGHT",
  SYSTEM_INTEGRATION_HTTP = "SYSTEM_INTEGRATION_HTTP",
}

export enum AGENT_TASKS {
  SYSTEM_CRAWL_ANALYSE = "SYSTEM_CRAWL_ANALYSE",
  SYSTEM_SEARCH_ENGINE = "SYSTEM_SEARCH_ENGINE",
  SYSTEM_COMPOSE = "SYSTEM_COMPOSE",
  SYSTEM_COMPOSE_AUDIO = "SYSTEM_COMPOSE_AUDIO",
  SYSTEM_COMPOSE_IMAGE = "SYSTEM_COMPOSE_IMAGE",
  SYSTEM_COMPOSE_VIDEO = "SYSTEM_COMPOSE_VIDEO",
}

export enum DATA_TASKS {
  SYSTEM_SQL_ANALYSIS = "SYSTEM_SQL_ANALYSIS",
  SYSTEM_SQL_INSIGHT = "SYSTEM_SQL_INSIGHT",
  SYSTEM_INTEGRATION_HTTP = "SYSTEM_INTEGRATION_HTTP",
}

export enum SystemPromptType {
  SYSTEM_COMPOSE = "Start Writing",
  SYSTEM_PROMPT_COMPOSE_OUTLINE = "Create Content Outline",
  SYSTEM_PROMPT_DATA_ANALYSIS = "Analyze Data",
  SYSTEM_PROMPT_SQL_ANALYSIS = "Data Insights",
  SYSTEM_PROMPT_DATA_CSV_ANALYSIS = "CSV Content Analysis",
  SYSTEM_PROMPT_DEFINE_DATA_ENTITY_STRUCTURE = "Extract Data Structure",
  SYSTEM_PROMPT_EXECUTION = "Prompting",
  SYSTEM_SEARCH_ENGINE = "Search online",
  SYSTEM_PROMPT_UPLOAD_ANALYSE = "Analyze Upload File(s)",
  SYSTEM_COMPOSE_AUDIO = "Generate Audio",
  SYSTEM_COMPOSE_IMAGE = "Generate Image",
  SYSTEM_COMPOSE_VIDEO = "Generate Video",
  SYSTEM_DATA_INTEGRATION = "External Data Analysis",
  SYSTEM_CRAWL_ANALYSE = "Crawler (Web)",
  CUSTOM_ACTION = "Custom Action",
  SYSTEM_SQL_ANALYSIS = "Data Analysis",
  SYSTEM_SQL_INSIGHT = "Insight Analyzer",
  SYSTEM_INTEGRATION_HTTP = "Webhook",
}

export enum NODE_CONFIG {
  WIDTH = 384,
  HEIGHT = 466,
}

export const styleNode =
  "w-[384px] justify-between rounded-xl border border-blue-500";
